<%@ page contentType="text/html;charset=UTF-8" language="java" isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<c:set var="pageTitle" value="Menu - Restaurant Booking" />
<c:set var="pageDescription" value="Explore our delicious menu featuring authentic Mexican cuisine including tacos, burritos, tamales and more." />
<c:set var="additionalCSS">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/menu.css">
</c:set>
<c:set var="additionalJS">
    <script src="${pageContext.request.contextPath}/js/menu.js"></script>
</c:set>

<jsp:include page="../common/layout.jsp">
    <jsp:param name="title" value="${pageTitle}" />
    <jsp:param name="description" value="${pageDescription}" />
    <jsp:param name="additionalCSS" value="${additionalCSS}" />
    <jsp:param name="additionalJS" value="${additionalJS}" />
    <jsp:attribute name="content">
        <!-- Banner Slideshow -->
        <div class="banner-slideshow">
            <div class="slides" id="slides">
                <c:forEach var="banner" items="${banners}" varStatus="status">
                    <div class="banner-slide">
                        <img src="${pageContext.request.contextPath}/assets/images/banner/${banner.image}" alt="${banner.title}">
                        <div class="banner-content">
                            <h1>${banner.title}</h1>
                            <p>${banner.description}</p>
                            <c:if test="${not empty banner.buttonText}">
                                <button class="order-btn" onclick="location.href='${banner.buttonLink}'">${banner.buttonText}</button>
                            </c:if>
                        </div>
                    </div>
                </c:forEach>
                
                <!-- Default banners if no dynamic content -->
                <c:if test="${empty banners}">
                    <div class="banner-slide">
                        <img src="${pageContext.request.contextPath}/assets/images/banner/banner0.png" alt="Welcome to Our Restaurant">
                        <div class="banner-content">
                            <h1>Authentic Mexican Cuisine</h1>
                            <p>Discover the flavors of Mexico</p>
                        </div>
                    </div>
                    <div class="banner-slide">
                        <img src="${pageContext.request.contextPath}/assets/images/banner/banner1.jpg" alt="Fresh Ingredients">
                        <div class="banner-content">
                            <h1>Fresh Ingredients Daily</h1>
                            <p>Quality you can taste</p>
                        </div>
                    </div>
                    <div class="banner-slide">
                        <img src="${pageContext.request.contextPath}/assets/images/banner/banner2.png" alt="Traditional Recipes">
                        <div class="banner-content">
                            <h1>Traditional Recipes</h1>
                            <p>Passed down through generations</p>
                        </div>
                    </div>
                </c:if>
            </div>
            
            <div class="dots" id="dots">
                <!-- Dots will be generated by JavaScript -->
            </div>
        </div>

        <!-- Menu Container -->
        <div class="menu-container">
            <div class="sidebar">
                <div class="dropdown">
                    <button class="dropdown-btn" onclick="toggleDropdown(); showCategory('popular')">
                        Most Popular <span class="arrow"></span>
                    </button>
                    <div class="dropdown-content" id="dropdownContent">
                        <c:forEach var="category" items="${menuCategories}">
                            <a onclick="showCategory('${category.slug}')">
                                <img src="${pageContext.request.contextPath}/assets/images/menu/${category.icon}" 
                                     alt="${category.name}" class="food-icon"> 
                                ${category.name}
                            </a>
                        </c:forEach>
                        
                        <!-- Default categories if no dynamic content -->
                        <c:if test="${empty menuCategories}">
                            <a onclick="showCategory('tacos')">
                                <img src="${pageContext.request.contextPath}/assets/images/menu/tacos.jpg" alt="Tacos" class="food-icon"> Tacos
                            </a>
                            <a onclick="showCategory('burritos')">
                                <img src="${pageContext.request.contextPath}/assets/images/menu/burrito.jpg" alt="Burrito" class="food-icon"> Burrito
                            </a>
                            <a onclick="showCategory('tamales')">
                                <img src="${pageContext.request.contextPath}/assets/images/menu/tamales.jpg" alt="Tamales" class="food-icon"> Tamales
                            </a>
                            <a onclick="showCategory('chiles')">
                                <img src="${pageContext.request.contextPath}/assets/images/menu/chiles.jpg" alt="Chiles en Nogada" class="food-icon"> Chiles en Nogada
                            </a>
                            <a onclick="showCategory('soups')">
                                <img src="${pageContext.request.contextPath}/assets/images/menu/soup.jpg" alt="Soup" class="food-icon"> Soup
                            </a>
                            <a onclick="showCategory('stews')">
                                <img src="${pageContext.request.contextPath}/assets/images/menu/stew.jpg" alt="Stew" class="food-icon"> Stew
                            </a>
                            <a onclick="showCategory('appetizers')">
                                <img src="${pageContext.request.contextPath}/assets/images/menu/appetizer.jpg" alt="Appetizer" class="food-icon"> Appetizer
                            </a>
                            <a onclick="showCategory('drinks')">
                                <img src="${pageContext.request.contextPath}/assets/images/menu/drinks.jpg" alt="Drinks" class="food-icon"> Drinks
                            </a>
                        </c:if>
                    </div>
                </div>
            </div>
            
            <div class="content" id="content">
                <h2>Select a category to view menu items</h2>
                <p class="menu-instruction">Choose from our delicious categories on the left to explore our authentic Mexican cuisine.</p>
            </div>
        </div>

        <!-- Hidden menu data for JavaScript -->
        <script type="application/json" id="menuData">
            <c:choose>
                <c:when test="${not empty menuItems}">
                    ${menuItemsJson}
                </c:when>
                <c:otherwise>
                    {
                        "tacos": [
                            {
                                "name": "Taco al Pastor",
                                "image": "taco_al_pastor.jpg",
                                "description": "Tacos with marinated pork, grilled on a rotisserie skewer, served with pineapple, onion and cilantro.",
                                "price": 35000,
                                "currency": "VND",
                                "isBestSeller": true,
                                "isAvailable": true
                            },
                            {
                                "name": "Taco de Carnitas",
                                "image": "taco_de_carnitas.jpg",
                                "description": "Tacos with tender braised pork, served with onions, cilantro and salsa.",
                                "price": 40000,
                                "currency": "VND",
                                "isBestSeller": false,
                                "isAvailable": true
                            },
                            {
                                "name": "Taco de Pescado",
                                "image": "taco_de_pescado.jpg",
                                "description": "Crispy fried fish tacos, served with cabbage, sour cream sauce and a squeeze of lime.",
                                "price": 48000,
                                "currency": "VND",
                                "isBestSeller": false,
                                "isAvailable": true
                            }
                        ],
                        "burritos": [
                            {
                                "name": "Burrito de Carne Asada",
                                "image": "burrito_de_carne_asada.jpg",
                                "description": "Grilled beef burrito, served with rice, beans, cheese and salsa.",
                                "price": 120000,
                                "currency": "VND",
                                "isBestSeller": true,
                                "isAvailable": true
                            },
                            {
                                "name": "Burrito de Pollo",
                                "image": "burrito_de_pollo.jpg",
                                "description": "Burrito with seasoned chicken, served with cheese, lettuce and creamy sauce.",
                                "price": 110000,
                                "currency": "VND",
                                "isBestSeller": false,
                                "isAvailable": true
                            }
                        ],
                        "popular": [
                            {
                                "name": "Taco al Pastor",
                                "image": "taco_al_pastor.jpg",
                                "description": "Tacos with marinated pork, grilled on a rotisserie skewer, served with pineapple, onion and cilantro.",
                                "price": 35000,
                                "currency": "VND",
                                "isBestSeller": true,
                                "isAvailable": true
                            },
                            {
                                "name": "Burrito de Carne Asada",
                                "image": "burrito_de_carne_asada.jpg",
                                "description": "Grilled beef burrito, served with rice, beans, cheese and salsa.",
                                "price": 120000,
                                "currency": "VND",
                                "isBestSeller": true,
                                "isAvailable": true
                            }
                        ]
                    }
                </c:otherwise>
            </c:choose>
        </script>

        <!-- Cart Modal -->
        <div id="cartModal" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h3>Add to Cart</h3>
                    <span class="close" onclick="closeCartModal()">&times;</span>
                </div>
                <div class="modal-body">
                    <div id="cartItemDetails"></div>
                    <div class="quantity-selector">
                        <label for="quantity">Quantity:</label>
                        <div class="quantity-controls">
                            <button type="button" onclick="decreaseQuantity()">-</button>
                            <input type="number" id="quantity" value="1" min="1" max="10">
                            <button type="button" onclick="increaseQuantity()">+</button>
                        </div>
                    </div>
                    <div class="special-instructions">
                        <label for="instructions">Special Instructions:</label>
                        <textarea id="instructions" placeholder="Any special requests or modifications..."></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" onclick="closeCartModal()">Cancel</button>
                    <button class="btn btn-primary" onclick="confirmAddToCart()">Add to Cart</button>
                </div>
            </div>
        </div>
    </jsp:attribute>
</jsp:include>